<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="project1" name="pytest" skipped="0" tests="1" time="0.843" timestamp="2021-08-15T15:32:04.582402"><testcase classname="" name="service_4.tests.test_unit_4" time="0.000"><error message="collection failure">venv/lib/python3.6/site-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
venv/lib/python3.6/site-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:994: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:955: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:665: in _load_unlocked
    ???
venv/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
service_4/tests/test_unit_4.py:4: in &lt;module&gt;
    from service_4.app import app, power
E     File "/home/MichaelRoy/Power_Scale/service_4/app.py", line 43
E       def post_power():
E         ^
E   SyntaxError: invalid syntax</error></testcase></testsuite></testsuites>